### PR TITLE
Check for NaNs and display counts in plot legend

### PR DESCRIPTION
**Pull request by kd0aij**

### CODE REVIEW

**Comment by DrTon** [comment]
IMO plot legend is not good place for this. And why you need this feature at all?

**Comment by kd0aij** [comment]
This allows one to tell whether missing data points are due to dropouts or NaNs. Only a developer would have need for it; Roman had some logs with NaNs, due to a code bug.

**Comment by DrTon** [comment]
Ok, got it. So the problem is actually more dev-friendly debugging. What about separate text console with debug messages (reporting about NaNs and logs from processors), so devs can add logs quickly?

**Comment by kd0aij** [comment]
that sounds like a much more useful mechanism than hacking the plot display

**Pull request closed without merging**
