### PR TITLE
Add "Display" button to toggle individual data series on/off

### PR DESCRIPTION
**Pull request by kd0aij**
not pretty, but it works

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Cool, I like the markers ;)
@kd0aij For the enabling/disabling I would propose to use a second column for the processor table with a checkbox in it. There exists a standard renderer for that (so you don't need to make the same effort as for the param able underneath it)

**Comment by AndreasAntener** [comment]
Oh it's just a list ATM, you'd have to switch to a table for that.

**Comment by DrTon** [comment]
@kd0aij, thank you but it is not pretty at all :) I've implemented it more elegant way, look "master" and test please. Closing this.

**Comment by DrTon** [comment]
What about markers - working on integration!

**Comment by kd0aij** [comment]
Thanks Anton. Looks nicer and easier to use too.

**Comment by kd0aij** [comment]
@DrTon I assume you'll want to move control of markers down to the processor or field level, and it sounds like you're working on that, so I won't put any more effort into my addMarkers branch

**Comment by DrTon** [comment]
Yes, I think about adding "line style" near "line color". But need to rework this part and fix some corner cases also.

**Comment by kd0aij** [comment]
I guess it would still be nice to be able to toggle markers on/off for all plots with a single click, since that is what I usually want to do.
I broke out the rest of the stuff that was in addDisplayButton to separate PRs so you can more easily decide what's useful.

**Pull request closed without merging**
