### PR TITLE
add binary op processor

### PR DESCRIPTION
**Pull request by kd0aij**
Hi Anton. I created a processor for binary operations, but as you pointed out, it doesn't fit very well with the selection mechanism in "Fields List". For now,  I just type in the desired fieldnames in the Parameters pane.
Just created the PR for communication purposes, though I don't think a merge would break anything.

### CODE REVIEW

**Comment by kd0aij** [comment]
binaryop

**Comment by AndreasAntener** [comment]
ok to test

**Comment by AndreasAntener** [comment]
Hi Mark
Cool! If you don't want to add a different type of parameter selection you could also just use the parameter "Fields" like the SimpleProcessor and only consider the first 2 fields (if the user would enter  a 3rd field for some reason..).
But yeah, someone needs to rewrite the param representation and selection anyway. I added color selections in PR #18 which is pretty hacky because of that too.
I think it makes sense to merge this and the color PR because they are useful. I'll do that in the next days if Anton doesn't oppose :). There should be no problem to refactor things if anyone wants to take on the task to rewrite param handling.
Cheers
ada

**Comment by kd0aij** [comment]
Thanks Andreas.
I thought it would be nice to do something like a pulldown list for field names 1 and 2. Since the order matters for operators like "-" it doesn't make as much sense to allow multiple selections. And it would make sense to organize the list into two levels; upper level for category like ARSP or SENS. Would make it easier to navigate to specific field names.

**Comment by AndreasAntener** [comment]
Ah you're talking about the field list. Multiple selections are already possible there (e.g. with the SimpleProcessor). But you're right of course, if the order matters it's a different case..
I'm not sure if splitting up the fields is such a good idea, at least now I can go through alphabetically. To find categories that make sense for most people is probably hard.

Merging this now

**Comment by kd0aij** [comment]
I was thinking of a popup menu which listed the existing categories (I expect "category" is the wrong term, maybe message type is more correct) alphabetically:
AIR1
AIRS
ARSP
...
Wind
perhaps adding a description column e.g. ARSP: Attitude Rate SetPoint
Clicking on one of these would pop up a second level menu e.g. for ATC1:
Pitch
Roll
Thrust
Yaw
Clicking on one of these would insert the selected value into the working field.
Of course this only works for single selections, but it could live in parallel with the existing Fields List selection mechanism without causing too much confusion.

**Comment by DrTon** [comment]
Hi! I have an idea how to organize parameters better for this processor. Will try later. Sorry for silence, a lot of things to do. Thank you all for the contributions!

**Comment by AndreasAntener** [comment]
I'll merge the color improvement, then you'll have the parameter table already ready for adding other editor controls (e.g. drop down)

**Pull request merged**
