### PR TITLE
Jenkins build integration

### PR DESCRIPTION
**Pull request by AndreasAntener**
Hey @DrTon, this adds a new ant target to create zip files of the artifacts and a build status image.

If you'd like to try the whole build circus with Jenkins, you would need to do the following configuration:
- add user "ada-ci" as collaborator
- add 2 web hooks (see screen shots, type needs to be form-urlencoded)

screen shot 2015-01-13 at 14 05 35
screen shot 2015-01-13 at 14 05 22

Cheers
ada

### CODE REVIEW

**Comment by AndreasAntener** [comment]
Just as a side note: for me this is an experiment with Jenkins because it's open source and I might need something for private repos (Travis costs a LOT of money for private repose).
If Jenkins works this will run as long as it's useful. But I don't mind if at some later point you/we decide that for all PX4 related projects Travis might be the better option (because it is maintenance free and it might make sense to use the same thing for related projects)

**Comment by DrTon** [comment]
Thanks for the contribution, but I have no free time to learn one more system now :( Just let me know when PR will be well tested ready to merge.

**Comment by AndreasAntener** [comment]
Ok, no problem. By "experiment" I didn't mean it doesn't work ;) It's actually ready to merge. But you will have to add the 2 webhooks and "ada-ci" as collaborator in FlightPlot project settings in order to make it work.

**Comment by AndreasAntener** [comment]
Test comment

**Pull request merged**
