### PR TITLE
common.xml update to latest mavlink 1.0

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by AndreasAntener** [comment]
@ada-ci add to whitelist

**Comment by AndreasAntener** [comment]
Side note: CI fails because mavlink_log branches are not up-to-date with master

**Comment by dagar** [comment]
What else needs to be done to get mavlink_log into master? I find it useful to plot my qgroundcontrol logs.

**Comment by AndreasAntener** [comment]
Does #13 still apply? I never tried this branch. @DrTon ?

**Comment by DrTon** [comment]
This branch worked for me, need to update and review. Also need to add schema xml selector GUI, to use custom schema. But first I would like to fix mess in parameters editor GUI in master. It's still not intuitive.

**Pull request closed without merging**
