### PR TITLE
[WIP] ULog format

### PR DESCRIPTION
**Pull request by bkueng**
This contains work in progress updates to support the new ULog logging format in PX4. It contains format breakages and thus needs to be in sync with the Firmware/new_logger_continued branch.

@kd0aij @dagar I forked the repo into PX4 space to facilitate collaboration. Feel free to push on this branch.

It builds on and replaces #63

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@DrTon If possible I'd to avoid having to maintain our own set of binaries for Flightplot. Would it be possible for you to be relatively responsive for this other PRs so we can avoid this?

**Comment by DrTon** [comment]
@LorenzMeier, sorry for the silence, I'm not checking updates on all my repos every day. Will try to tune notifications now. Anyway, if something important, please ping me on Skype/email please.

**Comment by DrTon** [comment]
Could anybody describe resulting log format?

**Comment by bkueng** [comment]
Yes it's on http://dev.px4.io/advanced-ulog-file-format.html
We don't plan to make any changes to this anymore, except if you have a very good reason. The new logger in PX4 generates files that are compatible with this branch. So it's important that we merge this.

**Pull request closed without merging**
